[app]
name = "EMF Map"
category = "Apps"

[entry]
class = "MapApp"

[metadata]
author = "Alexander Baxevanis"
license = "MIT"
url = "https://www.github.com/futureshape/emf-badge-map"
description = "View the EMF site map on your badge."
version = "0.1"
